# Generated by Django 5.1.2 on 2024-10-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelalivros",
            name="braile",
            field=models.BooleanField(default=False),
        ),
    ]
