# Generated by Django 5.1.2 on 2024-10-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_tabelalivros_braile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tabelalivros", options={"verbose_name": "Tabela_Livro"},
        ),
    ]
