# Generated by Django 5.1.2 on 2024-11-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_alter_tabelalivros_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaCategorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_categoria", models.CharField(max_length=30)),
                ("descricao", models.CharField(max_length=60)),
            ],
            options={"verbose_name": "Tabela_Categoria",},
        ),
        migrations.RemoveField(model_name="tabelalivros", name="cateoria",),
        migrations.AddField(
            model_name="tabelalivros",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="livros.tabelacategorias",
            ),
            preserve_default=False,
        ),
    ]
