# Generated by Django 5.1.2 on 2024-11-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_tabelacategorias_remove_tabelalivros_cateoria_and_more"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelalivros",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.tabelausuarios",
            ),
            preserve_default=False,
        ),
    ]
