# Generated by Django 5.1.2 on 2024-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0005_tabelalivros_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelalivros",
            name="imagem_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
