# Generated by Django 5.1.2 on 2024-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0006_tabelalivros_imagem_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tabelalivros", old_name="imagem_url", new_name="imagem_link",
        ),
        migrations.AddField(
            model_name="tabelalivros",
            name="imagem_upload",
            field=models.ImageField(blank=True, null=True, upload_to="livros_imagens/"),
        ),
    ]
