# Generated by Django 5.1.2 on 2024-11-08 05:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0007_rename_imagem_url_tabelalivros_imagem_link_and_more"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaTrocas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_proposta", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aceita", "Aceita"),
                            ("Rejeitada", "Rejeitada"),
                            ("Concluída", "Concluída"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "livro_oferecido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livro_oferecido",
                        to="livros.tabelalivros",
                    ),
                ),
                (
                    "livro_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livro_solicitado",
                        to="livros.tabelalivros",
                    ),
                ),
                (
                    "usuario_oferecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_oferecedor",
                        to="usuarios.tabelausuarios",
                    ),
                ),
                (
                    "usuario_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_solicitante",
                        to="usuarios.tabelausuarios",
                    ),
                ),
            ],
            options={"verbose_name": "Tabela_Troca",},
        ),
    ]
