# Generated by Django 5.1.2 on 2024-11-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0008_tabelatrocas"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelalivros",
            name="disponivel_para_troca",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tabelatrocas",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aceita", "Aceita"),
                    ("Rejeitada", "Rejeitada"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
