# Generated by Django 5.1.2 on 2024-11-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0009_tabelalivros_disponivel_para_troca_and_more"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabelatrocas",
            name="livro_oferecido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trocas_oferecidas",
                to="livros.tabelalivros",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatrocas",
            name="livro_solicitado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trocas_solicitadas",
                to="livros.tabelalivros",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatrocas",
            name="usuario_oferecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trocas_oferecidas_por_usuario",
                to="usuarios.tabelausuarios",
            ),
        ),
        migrations.AlterField(
            model_name="tabelatrocas",
            name="usuario_solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trocas_solicitadas_por_usuario",
                to="usuarios.tabelausuarios",
            ),
        ),
        migrations.CreateModel(
            name="Troca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aceita", "Aceita"),
                            ("Rejeitada", "Rejeitada"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "livro_oferecido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros_oferecidos",
                        to="livros.tabelalivros",
                    ),
                ),
                (
                    "livro_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros_solicitados",
                        to="livros.tabelalivros",
                    ),
                ),
                (
                    "usuario_dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trocas_dono_livro",
                        to="usuarios.tabelausuarios",
                    ),
                ),
                (
                    "usuario_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trocas_solicitantes",
                        to="usuarios.tabelausuarios",
                    ),
                ),
            ],
        ),
    ]
